version: '3.8'

services:
  thunes:
    build: .
    container_name: thunes-bot
    env_file:
      - .env
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    restart: unless-stopped
    command: python -m src.live.paper_trader --symbol BTCUSDT --quote 10 --tf 1h

  # Optional: Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: thunes-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  prometheus-data:
