# Grafana datasource provisioning - Prometheus
# Automatically configures Prometheus datasource on Grafana startup

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
