name: Paper Trading

on:
  workflow_dispatch:  # Manual trigger
  # DISABLED: Vectorbt/plotly incompatibility - re-enable after Phase 3.2
  # schedule:
  #   - cron: '*/10 * * * *'  # Every 10 minutes (staging)

concurrency:
  group: paper-trading
  cancel-in-progress: false

jobs:
  paper-trade:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: staging  # Requires manual approval

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a20  # v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies (with retry)
        uses: nick-fields/retry@ce71cc2ab81d554ebbe88c79ab5975992d79ba08  # v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 30
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run paper trading
        env:
          BINANCE_TESTNET_API_KEY: ${{ secrets.BINANCE_TESTNET_API_KEY }}
          BINANCE_TESTNET_API_SECRET: ${{ secrets.BINANCE_TESTNET_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TZ: ${{ vars.TZ || 'Europe/Paris' }}
          ENVIRONMENT: testnet
        run: |
          python -m src.live.paper_trader \
            --symbol BTCUSDT \
            --quote 10 \
            --tf 1h

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b  # v4.5.0
        with:
          name: paper-logs-${{ github.run_number }}
          path: logs/*.log
          retention-days: 7
